### ISSUE TITLE
Use dot or mermaid to render workflow graphs

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#1]
Graphs ideally are interactive so we can delete and insert nodes from the graph 

I think MVP for this is to use dot, as it's quick and simple and builds an svg which we can display inline with no other extra js.

* [ ] start by just getting the graph working at all showing all nodes and the connections, this could be an normal image file served through plugin file

All these actions would be possible without the graph so not critical and could be deferred

OR mermaid flowchart with interaction:
https://mermaid-js.github.io/mermaid/#/flowchart?id=interaction

**Comment by keevan** [comment]
Moved 2nd round to another issue: #54
