### ISSUE TITLE
Generic stream reader step

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#104]
We need to have a generic input stream reader. Testing is proving difficult without one.

- [ ] Source is a PHP stream.
- [ ] Specify the type and source  (and anything else needed) through the configuration.
- [ ] Input must be valid JSON. Reader will read the initial '[' during start up and check for a trailing ']' at the end.
- [ ] Must be able to specify a string input directly in the configuration.

**Comment by keevan** [comment]
I think it would be a mix of having a base class using the repository pattern to implement how it would read/write to and from particular data sources, e.g. a DB or PHP stream. 

All steps will already specify the type. The source can be a configuration parameter? e.g.
```
config:
  source: some-source
```

Generic contradicts with the need for it to be valid JSON. Perhaps a type of reader implements reading JSON, but I don't think the base class for this should implement anything in particular, and just follow the repository pattern / interfaces for data access.

> Must be able to specify a string input directly in the configuration.

Is this moreso for test data? Or actual input data as part of the configuration. I think the step implementation itself could expect the input (e.g. JSON) to come directly from the configuration if needed, and that would be fine.
