### ISSUE TITLE
Bug with sql step when run

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#111]
Exception - Return value of tool_dataflows\step\sql_reader::construct_query() must be of the type string, null returned

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

**Comment by jaypha** [comment]
Can you supply the flow you used that caused this error?

**Comment by brendanheywood** [comment]
[Uploading sql_+_mtrace_20220526_0527.yml.txt…]()

**Comment by jaypha** [comment]
The flow is lacking an actual SQL query. There is a validate function on the step type that checks this, but it does not appear be called.

**Comment by jaypha** [comment]
A new issue #118 has been created to address this problem.
Closing as no longer relevant.
