### ISSUE TITLE
Allow each step to define it's own form elements and validation

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#123]
Most likely three methods
* [ ] define standard form fields for a step
* [ ] a validaiton method
* [ ] optional extra form fields which are only for dry run. This way the fact that a step has any dry run options can be managed centrally

**Comment by keevan** [comment]
Noting that it would also be good to have a way to input the values directly as text if preferred - which goes through the same validation. This would also most likely apply to the "config" section as the other form inputs should be fixed.

**Comment by brendanheywood** [comment]
See #118

**Comment by brendanheywood** [comment]
I'm not seeing a good reason why but I think we need real world examples. In my mind typical config is say the textarea which defines the chunk of sql for the sql reader step. The step needs to say it is a textarea, and editing this and making sure it is escaped correctly manually editing it will be a bit meh. I think this will probably apply to all of the config items for all steps.

When we are done there should not be a generic 'config' text area

**Comment by keevan** [comment]
I was thinking the capability to switch between raw view and the forms (similar to WYSIWYG editors), as this should be exported one way or another anyways. 


A brief example would be 'Off-site collaboration': to allow one to more quickly paste configuration for a specific step, if the user needs to share it around for collaboration without giving access directly to the dataflow or exporting it and removing all the irrelevant bits. That said, a step export option would generally allow for the same thing. Once edited, it would be nice to paste in the updated config and see if they are valid. 

I do agree going forward that the configuration should be prominently done via some generated form inputs.

**Comment by brendanheywood** [comment]
I can't see it being easy to implement the swapper using formslib, it would probably be easier to have 2 forms and the raw one has no validation at all. I see it as fairly low value but I'm not opposed to it. I think just a step export and import is probably more useful in the short and long term
