### ISSUE TITLE
Be able to edit a workflow from the workflow details page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#125]

**Comment by keevan** [comment]
+1

With the page restructing and nav changes, I'll add a button to go to the edit dataflow page for this.

**Comment by brendanheywood** [comment]
While you are there lets move all the workflow buttons into one toolbar, edit, run, export, import

The 'add step' I think can stay where it is as it will probably expand into its own toolbar of all the groups of steps
