### ISSUE TITLE
Be able to disable and enable a workflow

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#126]
What this means is mostly dependent on the implementation of the trigger step, so each trigger will need to honor this in some way
* [x] regardless of how it is triggered it will not run
* [ ] each trigger step can take extra steps to avoid it being run in the first place, eg cron would filter these out in sql
* [x] dry run still works
* [x] manual run still works, eg you'd test stuff manually then when ready enable it to allow the trigger to take over
* [x] until the triggers are implemented later this really just sets a flag and is shown in the master index of workflows as a disabled row cell

**Comment by Peterburnett** [comment]
Im just jumping into this, but Im not sure that a trigger step should really need to care about whether it is executable. From the current architecture it seems that the trigger will just be responsible for the initialisation of the execution engine. I would expect (and have implemented the bones of) that the execution engine is responsible for whether its respected.

The enable is simply a flag in the DB for the workflow, so the task trigger for example *could* filter it, but it could also blanket initialise all, as the execution engine is ultimately deciding not to execute in that context anyway. Just my 2 cents
