### ISSUE TITLE
Processor call internal web service for each row

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#13]
Each argument to the webservice would be an expression

* [x] config for which web service to call
* [x] config for which user to pseudo as for the call, defaults to the admin / cli user
* [x] expression for the data pushed into the call
* [x] config for what to do if it fails, either record it and move on or abort the entire flow?

**Comment by keevan** [comment]
For what it's worth, trigger has existing web service handling, so you can borrow bits from there as needed.

https://github.com/catalyst/moodle-tool_trigger/blob/MOODLE_311_STABLE/classes/steps/actions/webservice_action_step.php#L128
