### ISSUE TITLE
json writing should have option to pretty print

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#141]
Even if pretty print is off, still add a linebreak after each record

**Comment by keevan** [comment]
I'm assuming the shape will be similar to the below, please clarify if I've misunderstood.

prettyprint:
```json
[{
    name: "Kevin"
},
{
    name: "James"
},
{
    name: "Icarus"
}]
```

no pretty print (something like this):
```json
[{name: "Kevin"},
{name: "James"},
{name: "Icarus"}]
```

The closing and end tags might change positions or be on their own line, unsure but I don't think it's important here. I think the important bit here is to ensure each record and subsequent record are formatted in a similar way, e.g. for readability.

**Comment by brendanheywood** [comment]
Essentially but slightly different, I just ran that example through json_pp:

$ cat ugly.json | json_pp

```json
[
   {
      "name" : "Kevin"
   },
   {
      "name" : "James"
   },
   {
      "name" : "Icarus"
   }
]
```

This should be a 1 liner:
```php
json_encode($json,JSON_PRETTY_PRINT );
```
