### ISSUE TITLE
Export internal state of workflow

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#187]
This will be conceptually similar to the export of a workflow and probably will extend on the yaml format of it. But this will include all of the state of a running instance, all its config, and all the variables and in what scope they are in.

* [x] When a workflow is run, or dry run, export the state at the end. This can just be a json dump on screen equivalent to the yaml export
* [x] An export in theory should be able to be run at any point during execution, eg we could also do a dump just prior to the workflow commencing
* [ ] this same export will be what we persist into the instance records for looking at previous runs, ie huge overlap with https://github.com/catalyst/moodle-tool_dataflows/issues/170
* [ ] #229

**Comment by keevan** [comment]
As the remaining points are linked to separate tasks, with the pausing and resuming one probably being another potentially larger task, I think it's safe to close off this one for now, as this was more or less an export of the state to the database run record / to the screen.

The other points are in addition to but not dependent for this issue. Please feel free to reopen if my understanding isn't correct.
