### ISSUE TITLE
Make logging more contextual

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#188]
Insteadof mashing all the logging info together into a string, lets pass in more optional context to the logging methods so that it can do smarter things with it. In particular lets pass in the step object to the log and not include an step related context in the string.

https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/local/execution/engine_step.php#L173-L175

https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/local/execution/engine.php#L264-L266

* [ ] pass in context, assume if no context then we are the manager
* [ ] when logging to mtrace just build the prefix up consistently from the step context

**Comment by jaypha** [comment]
Can you provide more details? I don't fully understand what you are thinking here.
