### ISSUE TITLE
Decide on architecture of how steps are declared

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#20]
Usual ideas:

1. sub plugins of this plugin
2. classes in this plugins
3. callback classes

Leaning towards 3) class which is some sort of callback. And then other plugins can implement their own steps. eg perhaps the steps for pushing to SNS or S3 could live inside local_aws and not in this plugin as an example.

**Comment by keevan** [comment]
Mostly in place now, just needs another plugin with the function defined in `lib.php` to confirm whether or not it's linking up as expected.

Making a note here to probably try it using via local_aws as an initial example.
