### ISSUE TITLE
Bug Crumb trails regression now missing from flow detail page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#216]
![image](https://user-images.githubusercontent.com/187449/174505338-62bcf764-f6a7-431e-8204-8416305d829b.png)

* [ ] /dataflows/view.php?id=1

**Comment by jaypha** [comment]
May I ask what version of Moodle you are using, and what theme?
Thanks.

**Comment by brendanheywood** [comment]
Latest master, default theme

**Comment by brendanheywood** [comment]
This was working last week, if I revert 2a3b0727e92a109abf36b1a969561efaaaae4684 then it all works again

**Comment by brendanheywood** [comment]
I've never seen the bug that you saw on https://github.com/catalyst/moodle-tool_dataflows/issues/212

I think the correct fix is to revert 2a3b072 and then conditionally add crumb nodes based on wether they already exist or not. The display of the nav nodes has changed a lot in 4.0 but the underlying api has not
