### ISSUE TITLE
Make sure only one cron trigger step per dataflow is allowed.

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#242]

**Comment by brendanheywood** [comment]
I'm on the fence around whether this is a cron trigger problem or a manager problem. On one hand I'm thinking that the simplest solution is the manager should just check that it only has 1 trigger step in the whole workflow, at the same place it does the DAG check. I think this is fine for MVP and beyond

In the very distant future maybe there is a work where a flow can have multiple triggers but really unsure if its a feature or not
