### ISSUE TITLE
debug logging

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#27]
Each step will have it's own concept of what to do if we are running in dry run mode. Mostly this only applies to sources and targets. A source will read from its test data instead of it's real data. And a target will just spit out something like a log with a curl command rather than making the api call.

At any given point in the progress of a workflow we will keep in memory stats on how many items have streamed through each step. In the summary logs for a workflow run we can show the graph and the number flows.

- [x] Debugging
- [x] Logging

**Comment by keevan** [comment]
Itemized items based on the description above (could be split out and some points may overlap with a different issue)

In dry mode:
- [ ] Source will read from its test data
- [ ] Target will output to log instead of performing the expected write/changes
- [ ] For other steps, it would probably be advised to only perform non permanent changes (e.g. don't insert/update the DB).

Other items which might be split out to a sub task
- [ ] All runs should record and measure the memory usage.
- [ ] Create and store results for a "run"
- [ ] Create a page to display the output/logs for a run

**Comment by jaypha** [comment]
Just how extensive should debugging be?
I currently have it so that a debug message is made for every attempt to execute a step, and also for every iteration on every iterator. For large data sets and complex dataflows, this could result in a TON of debugging messages.

**Comment by brendanheywood** [comment]
I see the dry run mode and the debugging as tangential so maybe we should split those up (see #90 )

Lets focus on the debug logging side for now. The main problem is you don't know what you want to see until something goes wrong in prod and you are trying to figure out what it did and where it busted. So lets focus on getting the mechanics of the debugging done first, the exact detail of what is logged and by what can evolve. I think at minimum we want to know when each connector step executes, and when flows start and stop, and if something barfs which thing barfed. We want generic logs to be emitted by the manager and also the ability for each step to emit its own extra stuff.

I'm on the fence around a log for each iterator record processed but it certainly cant hurt now and we can dial it back as we get closer to shipping. Maybe we want something like an aggregated status every nth record so we still get some sense of progress.

The other thing we need to get right is decoupling emitting logs from where they end up. They might end up in some combination of the cron logs, on screen in dry run mode, possibly persisting to their own log table or to the moodle log table. I think the events which end up in the moodle logs will be very simple, like an event when each dataflow finishes with some overall stats and not much more. The cron logs are probably the least important as they are not useful to an admin in the gui who may not be able to see them.

Echoing above, mvp here is:

* [ ] log interface for each step to use
* [ ] when you run an instance of a workflow persist its state at the start and then when it finishes so we can see what is running or has run
* [ ] have a log table of N logs per instance of a run and linked to a run.
* [ ] admin ui to view runs, and drill down from a run into its logs
* [ ] manager code to route log entries to the right place

**Comment by keevan** [comment]
Just to keep it relevant, comment based on discussion regarding state of things so far - https://github.com/catalyst/moodle-tool_dataflows/pull/100#pullrequestreview-985707043
