### ISSUE TITLE
Unit tests failing on local machine, despite passing on Github CI.

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#289]
This might be the cause.
https://github.com/catalyst/moodle-tool_dataflows/runs/7313125448?check_suite_focus=true#step:3:1975

**Comment by jaypha** [comment]
Full unit test output.

Moodle 3.9.14+ (Build: 20220617), 239e63380c8f4ea9a89133056261c8ccab8086f5
Php: 7.4.29, pgsql: 9.6.23, OS: Linux 5.15.0-39-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...............F.......FFF.........S............                  48 / 48 (100%)

Time: 8.42 seconds, Memory: 534.00 MB

There were 4 failures:

1) tool_dataflows\tool_dataflows_curl_connector_test::test_execute
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'curl -X POST http://download.moodle.org/unittest/test_post.php -d '{\n
                 "name": "morpheus",\n
                 "job": "leader"\n
-            }''
+            }'\n
+'

/var/www/dataflows/admin/tool/dataflows/tests/tool_dataflows_curl_connector_test.php:146
/var/www/dataflows/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/dataflows/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "tool_dataflows\tool_dataflows_curl_connector_test" admin/tool/dataflows/tests/tool_dataflows_curl_connector_test.php

2) tool_dataflows\tool_dataflows_secret_service_test::test_secret_redaction_in_logs_and_during_run
Failed asserting that 'Engine "s3 copy": status: new\n
Engine "s3 copy", step "s3copy": status: new\n
Engine "s3 copy", step "s3copy": status: initialised\n
Engine "s3 copy": status: initialised, config: {"isdryrun":false}\n
Engine "s3 copy": status: processing\n
Engine "s3 copy", step "s3copy": S3 copy failed. Please ensure you have getObject and putObject permissions on the target bucket.\n
Engine "s3 copy", step "s3copy": status: cancelled\n
Engine "s3 copy": status: finished\n
Engine "s3 copy", step "s3copy": status: finalised\n
Engine "s3 copy": status: finalised\n
Engine "s3 copy": dumping state..\n
global: {  }\n
env:\n
  DATAFLOW_ID: 330000\n
  DATAFLOW_RUN_ID: 333000\n
  DATAFLOW_RUN_NAME: 1\n
dataflow:\n
  name: 's3 copy'\n
  config: {  }\n
  states:\n
    new: 1657677690.8464\n
    initialised: 1657677690.8489\n
    processing: 1657677690.8558\n
    finished: 1657677691.0573\n
    finalised: 1657677691.0626\n
steps:\n
  s3copy:\n
    name: s3copy\n
    type: tool_dataflows\tiny_connector_s3\n
    config:\n
      bucket: bucket\n
      region: region\n
      key: SOMEKEY\n
      secret: OHNOYOUWERENTSUPPOSEDTOSEEME\n
      source: 's3://test/source.csv'\n
      target: 's3://test/target.csv'\n
      sourceremote: true\n
    alias: s3copy\n
    states:\n
      new: 1657677690.8485\n
      initialised: 1657677690.8488\n
      cancelled: 1657677691.0519\n
      finalised: 1657677691.0619\n
\n
' does not match PCRE pattern "/OHNOYOUWERENTSUPPOSEDTOSEEME/".

/var/www/dataflows/admin/tool/dataflows/tests/application_trait.php:75
/var/www/dataflows/admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php:154
/var/www/dataflows/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/dataflows/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "tool_dataflows\tool_dataflows_secret_service_test" admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php

3) tool_dataflows\tool_dataflows_secret_service_test::test_secret_redaction_for_exports
Failed asserting that 'OHNOYOUWERENTSUPPOSEDTOSEEME' is not equal to 'OHNOYOUWERENTSUPPOSEDTOSEEME'.

/var/www/dataflows/admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php:179
/var/www/dataflows/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/dataflows/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "tool_dataflows\tool_dataflows_secret_service_test" admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php

4) tool_dataflows\tool_dataflows_secret_service_test::test_secret_redaction_for_table_display
Failed asserting that '<nav aria-label="Page" class="pagination pagination-centered justify-content-center">\n
        <ul class="mt-1 pagination " data-page-size="0">\n
                <li class="page-item active" data-page-number="1">\n
                    <a href="#" class="page-link">\n
                        1\n
                            <span class="sr-only">(current)</span>\n
                    </a>\n
                </li>\n
        </ul>\n
    </nav><div class="no-overflow"><table class="flexible table table-striped table-hover generaltable generalbox"><thead><tr><th class="header c0" scope="col"><a data-sortable="1" data-sortby="name" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=name&amp;tdir=4](https://www.example.com/moodle/?tsort=name&tdir=4)">Name<span class="accesshide " >Sort by Name Ascending</span></a> <div class="commands"><a title="Hide Name" aria-expanded="true" aria-controls="" data-action="hide" data-column="name" href="https://www.example.com/moodle/?thide=name"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c1" scope="col"><a data-sortable="1" data-sortby="alias" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=alias&amp;tdir=4](https://www.example.com/moodle/?tsort=alias&tdir=4)">Alias<span class="accesshide " >Sort by Alias Ascending</span></a> <div class="commands"><a title="Hide Alias" aria-expanded="true" aria-controls="" data-action="hide" data-column="alias" href="https://www.example.com/moodle/?thide=alias"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c2" scope="col"><a data-sortable="1" data-sortby="description" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=description&amp;tdir=4](https://www.example.com/moodle/?tsort=description&tdir=4)">Description<span class="accesshide " >Sort by Description Ascending</span></a> <div class="commands"><a title="Hide Description" aria-expanded="true" aria-controls="" data-action="hide" data-column="description" href="https://www.example.com/moodle/?thide=description"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c3" scope="col"><a data-sortable="1" data-sortby="type" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=type&amp;tdir=4](https://www.example.com/moodle/?tsort=type&tdir=4)">Type of step<span class="accesshide " >Sort by Type of step Ascending</span></a> <div class="commands"><a title="Hide Type of step" aria-expanded="true" aria-controls="" data-action="hide" data-column="type" href="https://www.example.com/mood
le/?thide=type"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c4" scope="col"><a data-sortable="1" data-sortby="config" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=config&amp;tdir=4](https://www.example.com/moodle/?tsort=config&tdir=4)">Configuration<span class="accesshide " >Sort by Configuration Ascending</span></a> <div class="commands"><a title="Hide Configuration" aria-expanded="true" aria-controls="" data-action="hide" data-column="config" href="https://www.example.com/moodle/?thide=config"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c5" scope="col">Depends on<div class="commands"><a title="Hide Depends on" aria-expanded="true" aria-controls="" data-action="hide" data-column="dependson" href="https://www.example.com/moodle/?thide=dependson"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c6" scope="col"><a data-sortable="1" data-sortby="details" data-sortorder="4" href="[https://www.example.com/moodle/?tsort=details&amp;tdir=4](https://www.example.com/moodle/?tsort=details&tdir=4)">Details<span class="accesshide " >Sort by Details Ascending</span></a> <div class="commands"><a title="Hide Details" aria-expanded="true" aria-controls="" data-action="hide" data-column="details" href="https://www.example.com/moodle/?thide=details"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th><th class="header c7" scope="col">Actions<div class="commands"><a title="Hide Actions" aria-expanded="true" aria-controls="" data-action="hide" data-column="actions" href="https://www.example.com/moodle/?thide=actions"><i class="icon fa fa-minus fa-fw "  title="Hide" aria-label="Hide"></i></a></div></th></tr></thead><tbody><tr class="" id="dataflows_table_r0"><td class="cell c0" id="dataflows_table_r0_c0"><?xml version="1.0" encoding="UTF-8" standalone="no"?>\n
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n
\n
\n
<svg width="62pt" height="27pt"\n
 viewBox="0.00 0.00 62.00 27.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 23)">\n
<title>G</title>\n
\n
<g id="node1" class="node">\n
<title>s3copy</title>\n
<g id="a_node1"><a xlink:href="https://www.example.com/moodle/admin/tool/dataflows/step.php?id=331000" xlink:title="s3copy">\n
<polygon fill="#ffc107" stroke="transparent" points="54,-19 0,-19 0,0 54,0 54,-19"/>\n
<text text-anchor="middle" x="27" y="-7" font-family="Arial" font-size="10.00">s3copy</text>\n
</a>\n
</g>\n
</g>\n
</g>\n
</svg>\n
</td><td class="cell c1" id="dataflows_table_r0_c1">s3copy</td><td class="cell c2" id="dataflows_table_r0_c2"></td><td class="cell c3" id="dataflows_table_r0_c3">stepname</td><td class="cell c4" id="dataflows_table_r0_c4"><pre>bucket: bucket\n
region: region\n
key: SOMEKEY\n
secret: OHNOYOUWERENTSUPPOSEDTOSEEME\n
source: 's3://test/source.csv'\n
target: 's3://test/target.csv'\n
sourceremote: true\n
</pre></td><td class="cell c5" id="dataflows_table_r0_c5"><ul></ul></td><td class="cell c6" id="dataflows_table_r0_c6"></td><td class="cell c7" id="dataflows_table_r0_c7"><a href="https://www.example.com/moodle/admin/tool/dataflows/remove-step.php?stepid=331000&sesskey=DfroALbDj7" id="action_link62ce277b3467e1" class="" ><i class="icon fa fa-trash fa-fw "  title="Remove step" aria-label="Remove step"></i></a></td></tr></tbody></table></div><nav aria-label="Page" class="pagination pagination-centered justify-content-center">\n
        <ul class="mt-1 pagination " data-page-size="0">\n
                <li class="page-item active" data-page-number="1">\n
                    <a href="#" class="page-link">\n
                        1\n
                            <span class="sr-only">(current)</span>\n
                    </a>\n
                </li>\n
        </ul>\n
    </nav>' does not match PCRE pattern "/OHNOYOUWERENTSUPPOSEDTOSEEME/".

/var/www/dataflows/admin/tool/dataflows/tests/application_trait.php:75
/var/www/dataflows/admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php:225
/var/www/dataflows/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/dataflows/vendor/phpunit/phpunit/phpunit:60

To re-run:
 vendor/bin/phpunit "tool_dataflows\tool_dataflows_secret_service_test" admin/tool/dataflows/tests/tool_dataflows_secret_service_test.php

FAILURES!
Tests: 48, Assertions: 272, Failures: 4, Skipped: 1.

**Comment by keevan** [comment]
As mentioned in https://github.com/catalyst/moodle-tool_dataflows/issues/290, this issue will focus on fixing the failing tests.
