### ISSUE TITLE
Clarify permitted directories setting and provide examples

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_dataflows#297]
![image](https://user-images.githubusercontent.com/9924643/178861172-1e75c39d-1fbd-4a2f-990b-78bac4f03cc2.png)

- [ ] Currently difficult to know what sort of value should be entered here, so an example would be good.
- [ ] It would be good to have several formats / examples shown e.g. in the help text below so the user can determine if any of those are relevant.
- [ ] Allow generic placeholders for [dataroot] eg ```[dataroot]/import``` so you can make workflows more transferable between sites and they still work

Could potentially include an example step type that uses this, e.g. the writer_stream step via the stream name field

**Comment by jaypha** [comment]
For the place holders, there is Moodle's siteroot and dataroot. I'll add temp for the temp directory. Any others I should add?

**Comment by jaypha** [comment]
> It would be good to have several forms available e.g. in the help text below so the user can determine if any of those are relevant.
Could you expand on this. I don't quite understand it.
Thanks.

**Comment by keevan** [comment]
> 

Agreed. By default the dataflow should only ever be able to use things within the scratch dir (which is just an isolated space). I think sec wise, we'd pull in the things we want to work with into that scratch directory, and then anything goes in there. That said, I can see some value in letting this be configurable maybe, e.g. perhaps the site has access to some attached volume and they want things managed out of that space instead. 

This permitted_dirs setting should be locked and disabled (forced config) for our client sites though, since we don't want the dataflow to be able to reference absolutely anything in the underlying system (except maybe under dataroot as suggested previously).

For now I think clarifying what it can do is probably in scope of what this issue is about. If we decide to restrict it further or simply remove it (e.g. only scratch dir and dataroot locations are accessible) then we might not need this at all.

**Comment by brendanheywood** [comment]
The location of the scratch die already is configurable in a round about way, we use the moodle request dir api and it in turn has $CFG->localrequestdir you can use to tune where it lives.
