### ISSUE TITLE
Update steps to declare a list of exposed variables / available outputs that would be shown on the step forms

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_dataflows#308]
e.g. a curl step might say it can output the following:
- info
- httpcode
- connecttime
- totaltime
- sizeupload
- destination

The user can then use this information in the outputs field (described here #307) to use in subsequent steps.

Fixed fields should be defined, (e.g. `response.httpcode` or `response.totaltime`)
Dynamic fields should be indicated (e.g. `response.data.*`)

Each step is different so there might be varying degree of exposure of information. But having something there to start with will be good.

**Comment by marcghaly** [comment]
Adding step referencing to the user defined output mapping
