### ISSUE TITLE
Moodle event as a source trigger step

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#31]
This is an interesting idea, you can setup a flow which is triggered by a single event. This would create a stream which only has a single item in it. To some a large extent if this is all implemented really well tool_trigger would be redundant. 

If it is purely single instance then it is easy, we handle the event, put it into a tiny buffer, then call the flow execution manager which then pulls it through the flow. Possibly there is a case where many identical events are emitted by the same script as we could handle them as an actual stream. But this may be tricky as we don't want the flow manager to take over control of the script and be trying to pull more events out when it can't. OR even better, we can tell the flow manager to just run as much as it can, and then we'll pass execution back. We would probably need another method like 'is_waiting'

This will have some interesting edge cases to make sure we handle with filters. Because of a filter we can't know if there is items available until we actually ask for it. Because the filter won't know if it will return a record or not until it's gotten its data. So might fundamentally break us from using the iterator interface and we might need to introduce our own one. We can either return an item, or we can throw a 'flow is blocked' exception which exactly which source it is blocked on. We'd then want a resume flow method.

An extension of this concept is that all events are queued and there is config to say how much we should throttle / debounce the activation of the workflow. This means we'd pull out of the event queue at a latency no higher than X for event coming so we have some QoS around the overall latency but we are not smashing the dataflow manager with a high turnover of workflow instances.

**Comment by brendanheywood** [comment]
Some more thoughts on this:
1) the trigger should have an option to queue the events and then run these in an adhoc task, or it can ask for it to be blocking
2) it can only be blocking and done within the already running web process if the flow supports parallel flows. If not then it must be queued into an adhoc task
3) even if it is parallel then instead of having N processes each do their own then it should use queue_adhoc_task($task, true); to de-dup the tasks, and each task will attempt to drain the whole event queue

**Comment by brendanheywood** [comment]
Being devils advocate, if the flow is something like a curl, and that curl fails we'd want to re-try that specific data record and curl and let the others complete. So we either need a way to re-queue the ones which have failed, or better yet in this case we would make them async but have 1 task per flow and if the curl fails we re-try the whole adhoc task + flow with a single record. 

So the trigger config will have 3 options:

1)Synchronous, flow is done inside the original process
2) Asynchronous, one event per task, can be parallel, only works if the flow can be parallel
3) Asynchronous, in series, events are queued, each flow drains the queue

**Comment by matthewhilton** [comment]
Hi @brendanheywood I have been investigating this for a potential client and have come up with the following pseudo code to complete the three options you outlined - are you able to verify i'm understanding your requirements properly?

1) Synchronous, flow is done inside the original process
```
WHEN an event is observed
GET workflows that are listening to this event
FOREACH workflow
  IF workflow has option "Run immediately" selected
    EXECUTE the workflow
```

2) Asynchronous, one event per task, can be parallel, only works if the flow can be parallel
```
WHEN an event is observed
GET workflows that are listening to this event
FOREACH workflow
  IF workflow has option "parallel" selected
    CREATE adhoc task to execute workflow
```

3) Asynchronous, in series, events are queued, each flow drains the queue
```
WHEN an event is observed
PUSH event to event queue (? only enable if at least 1 event trigger is using this option)

WHEN tool_dataflows cron is called
GET events in event queue
FOREACH event in event queue
  DEQUEUE event
  GET workflows with option 'async in series' selected that are listening to this event
  FOREACH workflow
    CREATE adhoc task to execute workflow
```

I also had some discussions internally around how data should be exposed from each event. I can see that steps already have a $this->set_variables() function, but there was a suggestion that it be more generic:

> make it generic such that each step type can handle its own ingested data. For example, an event trigger might want to make the event available on `steps.eventtrigger.vars.event` instead of a more generic `steps.eventtrigger.vars.loadedcontent`. This would be useful later on for things such as a manual run trigger loaded with some custom data.

However I'm not entirely understanding what is meant by this since I don't have great knowledge of how variables are held inside steps. Some guidance here would be good.

**Comment by brendanheywood** [comment]
This is a good start, 1 and 2 are good. 3 the for each loops should be swapped and the loop of the events in the queue is done inside the flow as an iterator like the db read step. 

All the var interface stuff has already settled down so you should just follow the other steps on that front
