### ISSUE TITLE
Critical yaml exception bug

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#323]
http://moodle.local/admin/tool/dataflows/step.php?id=12 (json parse step)

pathtojson: types.json
arrayexpression: contentTypes
arraysortexpression: ''
sortorder: asc

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 141 of /admin/tool/dataflows/classes/dataflow.php: Error thrown
line 119 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->get_variables()
line 144 of /admin/tool/dataflows/classes/step.php: call to tool_dataflows\dataflow->__get()
line 99 of /admin/tool/dataflows/classes/form/step_form.php: call to tool_dataflows\step->get_variables()
line 214 of /lib/formslib.php: call to tool_dataflows\form\step_form->definition()
line 110 of /lib/classes/form/persistent.php: call to moodleform->__construct()
line 87 of /admin/tool/dataflows/step.php: call to core\form\persistent->__construct()

**Comment by keevan** [comment]
Also getting this oddly, probably related to the same underlying issue

![image](https://user-images.githubusercontent.com/9924643/180105261-4ead79d8-a8d6-474d-9fbd-3a14b2c6e70a.png)
