### ISSUE TITLE
Declare graphviz dependency properly

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-tool_dataflows#341]
Tasks:
* [x] On the main dataflows page show a warning if the dot path isn't a readable file
* [x] Show this on the admin settings page too
* [x] Whenever an image would have been shown, instead show a boilerplate fallback svg or images, or even just a plain red square or something rather than a raw error

---

Moodle: MOODLE_311_STABLE
Dataflows: MOODLE_35_STABLE 
as of today

This occurs on admin/tool/dataflows/view.php?id=1

```
Exception - failed to execute cmd: "dot -Tsvg". stderr: `sh: dot: command not found `

[More information about this error](http://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 105 of /admin/tool/dataflows/classes/visualiser.php: Exception thrown
line 331 of /admin/tool/dataflows/classes/visualiser.php: call to tool_dataflows\visualiser::generate()
line 68 of /admin/tool/dataflows/view.php: call to tool_dataflows\visualiser::display_dataflows_view_page()
×Dismiss this notification
```

As it turns out RTFM => graphviz must be installed.

Can it be declared in an environment.xml like this - https://github.com/maths/moodle-qtype_stack/blob/master/environment.xml ?

**Comment by aspark21** [comment]
https://docs.moodle.org/dev/Environment_checking
maybe...

**Comment by brendanheywood** [comment]
We did discuss this the other day in https://github.com/catalyst/moodle-tool_dataflows/issues/296 but obviously there is more to do. 

@aspark21 would you prefer an install blocking error message, or allow it to install and then a nicer error notification on the dataflow admin page saying what is wrong and how to fix it?

**Comment by brendanheywood** [comment]
In standup decided this should be runtime, because you can have it installed but need to configure the path so we want to avoid the chicken and egg

See also

https://github.com/catalyst/moodle-tool_dataflows/issues/315

**Comment by aspark21** [comment]
Yeah, in runtime will be most practical. 

environment.xml seemed like "the Moodle way" though I don't think I've seen it work against anything other than php extensions
