### ISSUE TITLE
Polish overview page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#352]
* [x] remove configuration column
* [x] remove steps count column
* [x] rename user column to what it is, ie Created by, or Last mod by
* [x] make the preview image have a maximum width and max height and let it auto scale
* [x] have a 'Last run' column with the human readable time since last run, eg 2 hours 3 mins ago

**Comment by jaypha** [comment]
I've been able to cap the width of the preview image, but have not figured out how to cap the height using bootstrap.

**Comment by brendanheywood** [comment]
Just inline css:

```
    max-height: 100px;
    max-width: 100px;
```

**Comment by jaypha** [comment]
For last run, do you want time started or time finished?

**Comment by brendanheywood** [comment]
Hmm, I think 2 cols, start time and duration
