### ISSUE TITLE
Allow access to selected global config variables such as wwwroot, primary user email, support email etc

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#366]
This would be available under vars something like

```
global.cfg.wwwroot
global.cfg.fullname
global.cfg.shortname
global.cfg.supportname
global.cfg.supportemail
global.cfg.supportpage
...
```

All keys should align 1-1 with the config values. This primary use case here is common elements that you would want to want to put into a message or email or notification eg #6

**Comment by jaypha** [comment]
A question. If the CFG setting is not set, do I include it as null, not include it at all, or make an error?
