### ISSUE TITLE
Permitted dirs must not evaluate to include empty strings

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#374]
Apparently exploding an empty string gives an array of one empty string.

**Comment by keevan** [comment]
Potentially, array_filter could be used on the result to remove the empty string entries.

**Comment by brendanheywood** [comment]
We've done this in other places where we do a 2 step cleanup, first removing anything that looks like a comment and then removing whitespace and empty lines

**Comment by jaypha** [comment]
Just to confirm that whitespace should be removed even though spaces are permitted in filenames?

**Comment by keevan** [comment]
I believe the whitespace removal suggestion is for lines containing only whitespace, and not white spaces in proper paths

**Comment by jaypha** [comment]
Do you think the setting should be cleaned before saving, or should it be saved as is? (It will be cleaned before using either way).

**Comment by keevan** [comment]
I believe there should be some form of cleaning before / as part of saving.

If the user has entered something invalid, it should show the originally submitted with the validation error below the field. I believe returning an errors['field'] does this automatically for you, so you don't have to worry about holding on to the original data. 

But once it's saved and is mostly in a valid shape, the data displayed post-saving, should reflect this good state. @brendanheywood mentioned the idea of having comments, etc. and if we decide to support these comments, I believe those comments should stay in the saved state, this would also need to preserve the spacing (whitespace) added if any, but I would for example trim the start and end. 

Sorry if the above was a bit of a brain dump but please do what you think is best, pragmatic and good for the user.

**Comment by brendanheywood** [comment]
I would expect something like this as potential input and I would expect it to save and persist exactly like this with whitespace intact:

```
# These paths are for the ETL foo bar
/some/path/
/some/other/path

# These paths are for enrolment
/more/foo    # This one is good
/more/bar    # This one is in testing

```

When it is parsed it would come out as

```
/some/path/
/some/other/path
/more/foor
/more/bar
```
