### ISSUE TITLE
s3 connector step should only have side effects if it copies to s3

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#378]
If it reads from s3 then it doesn't have any effect

**Comment by jaypha** [comment]
This is similar to #382.
Also for good measure, I will do this also for the curl connector.

**Comment by jaypha** [comment]
I noticed that the curl connector has an explicit 'has side effect' checkbox. I'm adding a has_side_effect() method to say true/false based on the destination and method values.

Is the checkbox still needed? If not, I will remove it.

**Comment by brendanheywood** [comment]
If we know that we are downloading a file and we write that file to outside the scratch dir then yes we know it was side effects. But if it doesn't then we don't know, so we will still need the checkbox either way
