### ISSUE TITLE
Improve the logging outputs and appenders

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#381]
There is a few things I'd like to see improved and they all interrelate:

* [x] I want to be able to have the engine and each step declare a log level for each message like debug, warn, error, critical etc and these will map to similar concepts in moodle, log4php, psr logs, etc
* [x] When running a flow you'll be able to set the log level depending on how much data you want to see. This can be set in the run now page as well as at the flow level
* [x] I want each message to be able to push both a free form string message as well as a structured data objects, usually this will be the state of the record which is flowing
* [x] I want there to be a concept similar to log4php of a log appender and we'd have a default one which appends using mtrace, but when running it in the run now page we could also have a browser devtool console appender
* [x] https://developer.mozilla.org/en-US/docs/Web/API/console/group

~~Rather than reinventing the wheel we just pull in log4php via composer and then write a couple appenders~~

**Comment by keevan** [comment]
>  When running a flow you'll be able to set the log level depending on how much data you want to see. This can be set in the run now page as well as at the flow level

This is set at the flow/site level, not on a run by run basis. If setting this on the run now page is still desired, it can be raised as a new issue.
