### ISSUE TITLE
Fix and improve the curl headers feature

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#392]
Tasks
* [x] remove the json and yaml parsing and just make this a raw text chunj
* [x] simply the text to just show the format for header: value
* [x] make it work with multiple headers
* [x] make the bash export also work with multiple headers
* [x] fix bash escaping

**Comment by brendanheywood** [comment]
Just put this back on the queue and re-done the task list here to be complete

**Comment by jaypha** [comment]
The headers field is currently designed to require RFC2616 compliance as requested in the comments to #466.
Could it be, perhaps, a bit looser to allow comments and blank lines, which would be removed before adding to curl?
