### ISSUE TITLE
Export and import stream setups

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#4]
All processors should have a standard way to store their internal config so we can have a generic way to export and import either a single step or a whole stream.

**Comment by keevan** [comment]
With the current state of things:
- [ ] Needs an import button on the GUI (import functionality is working, but needs file upload and handling for that)
- [ ] Needs an export button + functionality for it. 
- [ ] Add GUI to do so for individual steps as well.
