### ISSUE TITLE
When editing a step sometimes the link to its upstreams can get cut without warning

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#449]
Not sure what the conditions are to trigger this, eg this just got cut and I don't know why?:

![image](https://user-images.githubusercontent.com/187449/182998382-71760636-077c-45d1-aaa5-15677385e29b.png)

**Comment by brendanheywood** [comment]
I think is happening when something fails validation and then you re-save

**Comment by brendanheywood** [comment]
This is 100% related to the case statement and the named outputs, putputs can get rewired to the wrong output

**Comment by keevan** [comment]
Most likely an issue that was created before this was fix merged https://github.com/catalyst/moodle-tool_dataflows/pull/419

**Comment by brendanheywood** [comment]
This is possible an import error with dodgy data in the yaml from an old version of code, so sit on this for a bit
