### ISSUE TITLE
Have a 'wait' connector

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#45]
This is configured with an expression, probably an strtotime, and it will simply pause execution and then resume at that time. Probably needs to set the workflow into a blocked state and stop execution and queue up an adhoc task to resume it.

**Comment by keevan** [comment]
I'm concerned if one of the nodes / steps needs to wait, but another one (e.g. in the round robin) does not need to. Would pausing the workflow cause the other one to also be blocked? 

This may or may not be intended, and is similar to gates / branching logic but against an expressed time? (e.g. ensure 30 seconds have passed before continuing, or ensure an external api returns an OK before continuing)

**Comment by jaypha** [comment]
It is my current design that if one of the outputs is not ready, then it is simply skipped.

**Comment by brendanheywood** [comment]
With the original execution plan I had in mind is completely cleanly split the connector steps from the iterator steps so this wouldn't be an issue. The round robin pulling only happens within the context of a directly connected subgraph of iterator steps and a wait step by definition is outside this. If you looked at a complete setup, at any given time only exactly one connector would be running, OR exactly one connected iterator subgraph would be flowing.

> It is my current design that if one of the outputs is not ready, then it is simply skipped.

Don't quite grok this and would like to flesh that out more?

**Comment by jaypha** [comment]
> Don't quite grok this and would like to flesh that out more?

No really relevant anymore as Kevin is designing the branch steps.
