### ISSUE TITLE
Bug flow_web_service should pass the record onto the next

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#453]
flow_web_service::execute() returns a bool. As a flow step it should be returning a value, so it can be passed on the next step.
It appears to be written like a connector. Should 'result' perhaps be passed on through the flow iterator rather than set as a variable? (at least in addition to).
It is not identified as either a reader or a writer, even though it appears to be capable of both.

**Comment by keevan** [comment]
Yes it seems like it would in fact cause issues if any downstreams wanted to use the value. 

I do agree that a web service should be available as a connector and as a flow step, and @brendanheywood shares my sentiment as shown https://github.com/catalyst/moodle-tool_dataflows/issues/422 and https://github.com/catalyst/moodle-tool_dataflows/issues/377#issuecomment-1199339828

In the mean time, I do think the input should flow through as-is if it does not need to be touched.

**Comment by brendanheywood** [comment]
At the very least it should pass the record it was given on as-is. It definitely should not replace the record with the ws's output nor should it ever return false.

The semantics of a reader and a write are going to be gray for lots of step, I don't really think the labels as a perfect fit so I'm not super worried about those and they are mostly cosmetic anyway.

I can see use cases for both just stashing it somewhere like it is now, and also writing it into the record as an extra attribute somewhere. The middle ground is probably going to be config to say what to do with it, similar to the output mappings. I think we should split this up into 2 issues, and this one should only focus on the iterator return value being passed along the chain. The second part can wait, if we do end up refactoring things so a step can act and either a flow or connector depending on its config and context then that refactor should come first.
