### ISSUE TITLE
Allow any processor step to set variables in various scopes

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#5]
Each a simple processor could count the records that flow through the stream and then set the count in the stream scope which can be access in any expression. These are distinct from record scope variables which change for each record.

Each processor just gets a setter and a name, all variables are stored namespaced under the instance name of the step. A single processor plugin might  have many instances and both sets of vars need to be available. Each step will be given a default serial id but it can be set explicitly to something more human readable. 

There will be multiple 'scopes' that a var can be stored in:

1) 'step' scope / dataflow instance - this is essentially a temporary variable which is only in scope for the duration of a specific dataflow instance. If an instance is suspended, or finishes, then all this state will be persisted so we can see what happened. If suspended then we need the state in order to hibernate the instance and continue it in a new process. There is not an expectation that the state will be continously persisted so it will not be visible from outside the running process. So effectively an in memory set of vars.

2) 'flow' dataflow scope - this is a scope for a dataflow, rather than an instance of a dataflow. So for example if a step wants to do delta imports it must store the last timestamp it processed and that needs to persist across multiple instances of a dataflow. 

3) 'global' scope - these are for variables which span all dataflows. They can be read and written by any step but generally they would be set

Vars can be set by the admin author of a dataflow at all three levels. Vars at any level can also be force set in config.php so they are read only.

There will be namespaces for all vars which applies to all;

a) each step has a unique id within a dataflow, this id will be the namespace for its vars.

eg a step called 'logsql' which does delta's would store call setValue('flow', 'timestamp', now()) and this would end up in

flow.logsql.timestamp =123456789

b) the flow will have it's own namespace of 'config' for vars set by the admin at authoring time

flow.config.foo = bar

c) global vars eg shared connection string params

global.config.hrdb = xyz
global.config.hrpassword = xyz

Thinking these should be another persistent, and we should record who last edited it as well as if it was set from a running instance of manually.

**Comment by keevan** [comment]
Potentially the scopes and storage can be split as follows:
- "global" will be stored via set_config under the plugin scope. Storing it here makes sense as it will pass the requirement that it needs to be global accessible across all current + future runs for dataflows.
- "flow" will be stored under the dataflow (persistent) configuration, as this is settable at authoring time, and is persistent across dataflow instance runs. Think of it like setting a `config: ...` at the top level of the dataflow.yml file
- "instance" will be stored against the specific instance or run of that dataflow. 

Things on a more specific scope will be preferred to things at a larger scope, the only exception to this is configuration that has been forced via config.php which should never change.

Will add more detail here as it progresses.

**Comment by brendanheywood** [comment]
Mixing the plugin vars with moodle config has some risks, as long as the config is prefix and a flow cannot read normal config, and it cannot write to arbitrary config then this is ok
