### ISSUE TITLE
Exception in shutdown function after unit tests

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#512]
This happens after a unit test run
```
Exception ignored in shutdown function Closure::__invoke: Attempting to change the status of a dataflow engine after it has concluded.
```
Whatever it is, I'm fairly sure we don't want it.

**Comment by brendanheywood** [comment]
@petersistrom fyi regression, need to handle the case where one, or possible many flows have started and stopped and then finally the php script ends we need to only ever touch the last one and only if it wasn't actually running
