### ISSUE TITLE
Accessing record.* in an expression

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_dataflows#515]
https://github.com/catalyst/moodle-tool_dataflows/blob/dae50306f3cde81f83165b22ceb513997374a96b/classes/local/execution/flow_engine_step.php#L95

Currently it can be accessed as an expression via something like `${{ record["myfield"] }}` which is fine, but it is cumbersome to type for an end user and could be replaced with `${{ record.myfield }}` instead which conveys the same intent and does not require a cast. However, the issue with this is if the field was `my field` (with a space), there is no way to currently access it in object form.

Would it make sense to prefer the dot syntax (for all the benefits, consistency, ease of use, probably easier to read), in spite of not being able to reference the field at all via an expression? 

I'm leaning towards preferring the dot syntax, since having a key with a space should be uncommon and probably non standard in practice - which can be created via the SQL reader and loading a JSON file with a key containing spaces.

**Comment by brendanheywood** [comment]
I think we should encourage the readers to never write vars with spaces, they can use a helper which does the same convertion that the step name -> alias does
