### ISSUE TITLE
BUG Setting an output mapping to a previous value doesn't work if the previous value is an array

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#524]
[Single_web_service_call_20220809_0217.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/9286227/Single_web_service_call_20220809_0217.yml.txt)

In the output setting the vars the first time works but then copying those vars works for ints but not for arrays:

![image](https://user-images.githubusercontent.com/187449/183549128-3e54f462-d8f7-452a-8cbe-6c9aad9fe79f.png)

**Comment by jaypha** [comment]
The good news is that the outputs are defined correctly, it is just the display which is in error. 
The display is in error most likely because of #517. (The arrays had been converted to objects. When I converted them back to arrays, they displayed correctly).
So fixing #517 should also fix this.

**Comment by marcghaly** [comment]
Also @jaypha, the `set_output` is not the main culprit here, the cast here is proper https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/step.php#L908, issue is coming from here  https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/local/step/flow_logic_case.php#L211 when retrieved all is an stdclass
