### ISSUE TITLE
Compression/decompression steps

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#628]
Steps to compress and decompress.
- Select algorithm from a list (zip, gz, bz2, 7z etc).
- Read/write either files or variables. (Perhaps only variables and use in conjunction with #627)
- Connector and flow variants.

**Comment by brendanheywood** [comment]
Re files vs vars I would avoid loading large things into memory

**Comment by keevan** [comment]
+1 I think it's best to only handle things via files, and for actual high performance low memory usage use cases, we add support for anything else, when required.
