### ISSUE TITLE
Update references to `set_variables` in the docs

### ISSUE THREAD

**Issue by matthewhilton** [catalyst/moodle-tool_dataflows#666]
Since https://github.com/catalyst/moodle-tool_dataflows/pull/652/files `set_variables` has been removed. However, there are still some references to it in the docs that need to be updated.

**Comment by keevan** [comment]
Alongside phpdocs, this should also be updated.

https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/NEW_STEP.md
