### ISSUE TITLE
New connector to create a dir with a dynamic name

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_dataflows#677]
This would help to organise folder structure and back up files copied from SFTP to folders with dynamic names, eg YYYYMMDDHHMI

**Comment by dmitriim** [comment]
This could be done by using variables.
E.g. in my sftp_directory_file_list in the beginning of the flow I create date variable like `date: ${{ time() }}`
Then in sftp_file_copy I use it in the target as `/tmp/${{steps.sftp_directory_file_list.vars.date}}/${{record.filename}} ` which creates a unique dir.
