### ISSUE TITLE
New connector to copy files locally

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_dataflows#678]
That would cover a need to copy files locally from one folder to another.

The whole case would be like:
1. Create a backup dir with name like YYYYMMDDHHMI;
2. Copy files from SFTP to the YYYYMMDDHHMI dir (back up the files);
3. Copy files from YYYYMMDDHHMI dir to a static dir overriding existing files;

**Comment by jaypha** [comment]
Resolved by #728
