### ISSUE TITLE
Aborted flows display the wrong "finish time"

### ISSUE THREAD

**Issue by matthewhilton** [catalyst/moodle-tool_dataflows#681]
If a flow gets aborted the finish time displays in the UI as `1 January 1970, 10:00:00 AM` probably because it is unix time 0.

Ideally, this should show the time it was aborted, or nothing at all.

**Comment by brendanheywood** [comment]
+1 for the abort time rather than empty

**Comment by matthewhilton** [comment]
Just noticed as well, this means when a flow gets aborted, the "Manage flows" page shows that is has been running for hours (when it actually hasn't)

E.g. I found one that was "running for 16 hours" but it actually just aborted 16 hours ago
