### ISSUE TITLE
Add a 'description' field to the dataflow definition.

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#704]

**Comment by keevan** [comment]
Hi Jason, where this is intended to be used / displayed? I'd like to get a better picture.

**Comment by brendanheywood** [comment]
+1 for this, I actually thought we already had it. I think this has value even if it is only shown in the editing form for the flow

**Comment by jaypha** [comment]
It will appear in the editing form, of course. It will also appear in the exported YAML.
It could appear in the dataflow list, and on the dataflow overview page.
