### ISSUE TITLE
There is no way to alter data being passed through a flow step

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#716]
Currently, a step should be able to alter the data being passed down a flow iteration by returning a new value.
This value, however, is not set anywhere and is ultimately thrown away.

**Comment by keevan** [comment]
My understand of its current state is:
- flows will return the $input through (perhaps modified), and if the input should not flow through, it will pass a non-truthy value (e.g. false) instead
- connectors will pass true or false, but will only check on false explicitly to stop it from continuing.
- there are some steps which have been updated to have execute be the main entrypoint, but another "run" function is used to process the inputs and configuration provided as if it was called directly (like in more functional programming)

As such, I do believe the $input (or record) can be modified and should look modified as it is passed through to future steps. If this is not happening this is definitely a bug.

**Comment by jaypha** [comment]
Fixed by #718
