### ISSUE TITLE
SQL flow step doesn't expose the exception message for DML exceptions

### ISSUE THREAD

**Issue by Peterburnett** [catalyst/moodle-tool_dataflows#723]
The message contains the DB message, eg relation does not exist, so it should be thrown back out

**Comment by keevan** [comment]
Can you give an example query we can use to plug into the step, to test and fix it more quickly? I'd like to understand/see what it's currently doing now and what is expected instead.

Even better if you can paste a minimal exported dataflow example.

**Comment by Peterburnett** [comment]
`SELECT  * {mdl_courses}` this will explode, as courses isn't a real relation, but at first glance its a little opaque what is actually going wrong

**Comment by Peterburnett** [comment]
![image](https://user-images.githubusercontent.com/21162968/235833462-f431e279-aa16-411a-90a8-2261a9b4611a.png)
