### ISSUE TITLE
Allow steps to declare if they change external state or not

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#74]
eg if you have a workflow which pulls data, and then does 5 filters on it, then we would consider that a valid workflow. But it doesn't actually do anything. We want to be able to say have a step which updates something, or sends an email etc. These steps would be declared as changing state. A valid workflow must have all finishing steps in the graph change state?? Maybe this is a warning not an error, we will want to run half authored workflows which might not do anything yet.

* [ ] This can apply to flow steps or connector steps
* [ ] show these in the table, maybe something like a lightning icon
* [ ] Show these in the graph visually somehow, maybe a color or dotted border (will also depend on if it is a connector or flow step)

**Comment by keevan** [comment]
A name for the step property could be `hassideeffects` (has side effects) or similar.

> ...a side effect if it modifies some [state](https://en.wikipedia.org/wiki/State_(computer_science)) variable value(s) outside its local environment, which is to say if it has any observable effect other than its primary effect of returning a value to the invoker of the operation

Source: https://en.wikipedia.org/wiki/Side_effect_(computer_science)

**Comment by brendanheywood** [comment]
+1
