### ISSUE TITLE
thirdpartylibs missing vendor/symfony/cache-contracts

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_dataflows#895]
tbh - I'd be more inclined to just include vendor/symfony on it's own rather than each lib inside the folder - that way all of /vendor/symnfony is excluded from the codechecker stuff.

**Comment by danmarsden** [comment]
also missing vendor/symfony/event-dispatcher-contracts

note that this is probably a blocker for plugins db approval.

**Comment by djarran** [comment]
Hey @danmarsden, I have added the two missing libraries to the thirdpartylibs.xml file in #899.

In terms of just including only vendor/symfony, I'm unsure which vendor/symfony/ version to specify in the file.
