### ISSUE TITLE
some styles not specific enough

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_dataflows#896]
https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_401_STABLE/styles.css#L62-L99

in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by djarran** [comment]
This should be resolved by PR https://github.com/catalyst/moodle-tool_dataflows/pull/900
