### ISSUE TITLE
Dry run mode

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#90]
Rough outline: (split from #27)

* [ ] each step will declare if it changes state
* [ ] if it changes state when each step implements its own behavior, possibly with extra config, to say what it should do in dry run mode. 
* [ ] eg an email step could send the email to an alternate email
* [ ] other steps like updating a db could just do nothing, but log what they would have done
* [ ] the same logic applies to source steps, when in dry run mode each decides what they could do. A db reading step could instead just spit out a tiny subset of the data, eg the first N rows. or it could spit out some static data configured in the step setup

**Comment by jaypha** [comment]
This looks very step specific. It seems that all the engine has to do is maintain an 'isdryrun' flag, and the steps do the rest.
In this case I need more specific details of what each step type is expected to do.
The three step types currently defined that would be affected are sql_reader, debugging and mtrace. Could you provide specifics on what these should do?
Thanks.

**Comment by brendanheywood** [comment]
The debug and mtrace steps will be removed eventually so ignore them. Sql reader, and all reader steps might not need to change because they don't cause side effects. Maybe if the recordset is huge the dry run would limit it to say 100 or something which would step specific config. 

So first get the manager mechanics of this working, and then probably work on an easy step which writes as the test case. Some candidates are an sql insert step which would roll back a transaction instead of commit it if in dry run, or a url curl step which instead dumps the curl command to logs and does nothing if in dry run mode. We will want both eventually anyway.
